import "./globals.css";
import { Inter } from "next/font/google";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en" data-theme="business">
      <body className={inter.className}>
        <h1 className="bg-primary text-primary-content p-4 text-2xl text-center">Restaurant Picker</h1>
        {children}
      </body>
    </html>
  );
}
